---
- name: Install git
  hosts: app
  become: true
  tasks:
    - apt:
        name: git
        state: present
        update_cache: yes
- name: Clone
  hosts: app
  tasks:
    - name: Clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit
